name: Auto Merge PR

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Print TOken
        run:   |
          echo ${{ secrets.ADMIN_TOKEN }}
      
      # Auto-approve the pull request
      - name: Auto-approve PR
        id: auto_approve
        uses: hmarr/auto-approve-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
    
